# Generated by Django 5.1.5 on 2025-01-21 10:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_management', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appuser',
            name='address',
            field=models.ForeignKey(db_column='address_id', on_delete=django.db.models.deletion.CASCADE, to='customer_management.address'),
        ),
        migrations.AlterField(
            model_name='customerrelationship',
            name='appuser',
            field=models.ForeignKey(db_column='appuser_id', on_delete=django.db.models.deletion.CASCADE, to='customer_management.appuser'),
        ),
    ]
