# Generated by Django 5.1.5 on 2025-01-25 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_management', '0002_alter_appuser_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appuser',
            name='first_name',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='customerrelationship',
            name='points',
            field=models.IntegerField(db_index=True),
        ),
    ]
